In [2]:
from Functions import create_circuit_Unitary
from Gates import Tof
import numpy as np

Toffoli = Tof()

candidates = {
    "I":  [0, 0, 0],
    "T":  [0, 0, np.pi/4],
    "T_ad":[0, 0, -np.pi/4],
    "S":  [0, 0, np.pi/2],
    "S_ad":[0, 0, -np.pi/2],
    "H": [np.pi/2, 0, np.pi]
}

results = []

for gate1, p1 in candidates.items():
    for gate2, p2 in candidates.items():
        parameters = p1+p2
        U = create_circuit_Unitary(parameters)

        if np.allclose(U,Toffoli):
            results.append((gate1,gate2))

print(results)

[('H', 'T_ad')]


In [1]:
from Functions import create_circuit_Unitary
from Gates import Tof

from scipy.optimize import minimize
import numpy as np

Toffoli = Tof()

"""
def loss_function(parameters):
    U = create_circuit_Unitary(parameters)
    return np.linalg.norm(U - Toffoli, 'fro')**2
"""
def loss_function(parameters):
    U = create_circuit_Unitary(parameters)
    phase = np.angle(np.trace(U.conj().T @ Toffoli))
    return np.linalg.norm(U - np.exp(1j*phase)*Toffoli, 'fro')**2

#Parameters guess for U3_1 and U3_2
parameters = [np.pi/2, 0, np.pi, 0, 0, -np.pi/4]


result = minimize(loss_function, parameters)

print("Optimization result:")
print(result)


Optimization result:
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 7.779819766487872e-31
        x: [ 1.571e+00  0.000e+00  3.142e+00  0.000e+00  0.000e+00
            -7.854e-01]
      nit: 0
      jac: [ 2.980e-08  1.490e-07  1.490e-07  2.980e-08  1.490e-07
             1.490e-07]
 hess_inv: [[1 0 ... 0 0]
            [0 1 ... 0 0]
            ...
            [0 0 ... 1 0]
            [0 0 ... 0 1]]
     nfev: 7
     njev: 1
